### PR TITLE
Port "Improve touchscreen dragging"

### PR DESCRIPTION
**Pull request by bdero**
From https://github.com/open-craft/jsinput-vectordraw/pull/32

Internal issue: https://tasks.opencraft.com/browse/OC-1889

### Testing instructions (Using the built in Chromium device emulator):
1. Setup a devstack.
1. Install this xblock on this branch into the edxapp Python virtualenv.

    ```bash
# In the same directory as your Vagrantfile:
vagrant ssh -- sudo -u edxapp /edx/bin/pip.edxapp install -e git+https://github.com/open-craft/xblock-vectordraw.git@bdero/port-mobile-dragging-fix#egg=vectordraw-xblock
    ```
1. Run Studio
1. Navigate to a course, and then "Settings > Advanced Settings".
1. Update the "Advanced Module List" field to contain `["vectordraw"]`.
1. Click "Save Changes".
1. Navigate to the outline and create a new Section, Subsection, and Unit. You will be redirected to the Unit authoring view.
1. Select "Advanced > Vector Drawing" to create a new Vector Drawing problem.
1. Click "Edit".
1. Set the "Vectors" field with the following block:

    ```json
[
    {
        "name": "1",
        "description": "Vector 1",
        "coords": [
            [
                2.6877256317689535,
                1.3971119133574006
            ],
            [
                2.6877256317689535,
                4.397111913357403
            ]
        ],
        "type": "vector",
        "render": false,
        "length_factor": 1,
        "length_units": "",
        "base_angle": 0,
        "style": {
            "pointSize": 1,
            "pointColor": "red",
            "width": 4,
            "color": "blue",
            "label": null,
            "labelColor": "black"
        },
        "tail": [
            2.6877256317689535,
            1.3971119133574006
        ],
        "tip": [
            2.6877256317689535,
            4.397111913357403
        ],
        "length": 3.000000000000002,
        "angle": 90
    },
    {
        "name": "2",
        "description": "Vector 2",
        "coords": [
            [
                -1,
                1
            ],
            [
                -0.9999999999999998,
                4
            ]
        ],
        "type": "vector",
        "render": false,
        "length_factor": 1,
        "length_units": "",
        "base_angle": 0,
        "style": {
            "pointSize": 1,
            "pointColor": "red",
            "width": 4,
            "color": "blue",
            "label": null,
            "labelColor": "black"
        },
        "tail": [
            -1,
            1
        ],
        "tip": [
            -0.9999999999999998,
            4
        ],
        "length": 3,
        "angle": 90
    }
]
    ```
1. Set the "Expected result" field to the following block:

    ```json
{
    "1": {
        "tail": [
            2.69,
            1.4
        ],
        "tail_tolerance": 1,
        "tip": [
            2.69,
            4.4
        ],
        "tip_tolerance": 1
    },
    "2": {
        "tail": [
            -1,
            1
        ],
        "tail_tolerance": 1,
        "tip": [
            -0.9999999999999998,
            4
        ],
        "tip_tolerance": 1
    }
}
    ```
1. Click "Save".
1. Click "Publish".
1. Launch Chromium and navigate to the Vector Drawing problem in the LMS.
1. Create two vectors by clicking "Add Selected Force" twice.
1. Press `Ctrl+Shift+J` to launch the Chromium inspector tools.
1. Click the "Toggle device toolbar" button (screenshot) to launch the mobile device emulator.
1. Click and drag the vectors and their points in various ways. Notice that there are *no unregistered clicks*.

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@bdero Probably it is a bug n Chrome/Chromium, but I've observed the following:

1. When the problem is opened in "normal" mode  everything works as expected.
2. After switching to mobile emulation mode, everything still works as expected.
3. After quitting mobile emulation mode, drag events are ignored - you can no longer drag anything. Resetting the problem with "reset" button restores the functionality, as well as refreshing the page.

Not sure if we need to address that.

**Comment by e-kolpakov** [comment]
@bdero `objectsUnderMouse` no longer accept any parameters, while the only call to it still passes coordinates: https://github.com/open-craft/xblock-vectordraw/blob/d27bd4655823616de40c4561a97906fdd3fdb2c1/vectordraw/public/js/vectordraw.js#L427

**Comment by e-kolpakov** [comment]
@bdero other than that looks good. :+1: conditional `objectsUnderMouse` call is updated.

- [x] I tested this: vectordraw XBlock works in mobile emulation mode
- [x] I read through the code
- [ ] ~~Includes documentation~~ - no user/developer-facing changes - no docs to update.

**Comment by bdero** [comment]
@e-kolpakov Thanks for the review! Yeah, I think that's a bug with the device emulator and it seems to work again after a refresh. As long as it works in both modes without switching back and forth, I think it's safe to say it works. Good catch with the extra objectsUnderMouse param, I removed it and pushed.

**Pull request merged**
